version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-logical
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: Asia/Jakarta
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres 
      -c wal_level=logical 
      -c max_replication_slots=10 
      -c max_wal_senders=10
      -c timezone='Asia/Jakarta'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - etl-network

  pg_postgis_cdc:
    image: postgis/postgis:16-3.4
    container_name: postgis_container
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Jakarta
    ports:
      - "5434:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    command: >
      postgres 
      -c wal_level=logical 
      -c max_replication_slots=10 
      -c max_wal_senders=10
      -c timezone='Asia/Jakarta'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - etl-network

  pg_postgis_cdc_target:
    image: postgis/postgis:16-3.4
    container_name: postgis_container_target
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Jakarta
    ports:
      - "5435:5432"
    volumes:
      - postgis_data_target:/var/lib/postgresql/data
    command: >
      postgres 
      -c wal_level=logical 
      -c max_replication_slots=10 
      -c max_wal_senders=10
      -c timezone='Asia/Jakarta'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - etl-network

  pg_postgis_cdc_target_2:
    image: postgis/postgis:16-3.4
    container_name: postgis_container_target_2
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Jakarta
    ports:
      - "5436:5432"
    volumes:
      - postgis_data_target_2:/var/lib/postgresql/data
    command: >
      postgres 
      -c wal_level=logical 
      -c max_replication_slots=10 
      -c max_wal_senders=10
      -c timezone='Asia/Jakarta'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - etl-network
  
  rosetta-redis:
    image: redis:7
    command: ["redis-server", "--port", "6379"]
    volumes:
      - rosetta_redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - etl-network
    restart: unless-stopped

volumes:
  postgres_data:
  postgis_data:
  postgis_data_target:
  postgis_data_target_2:
  rosetta_redis_data:

networks:
  etl-network:
    driver: bridge